[project]
name = "backend"
created = "2025-12-25T15:23:38.586645"
framework_version = "0.6.0"
secrets = ".env"

[cli]
version = "1.0.0"
command = "co init"
template = "none"

[agent]
algorithm = "ed25519"
default_model = "co/gemini-2.5-pro"
max_iterations = 10
created_at = "2025-12-25T15:23:38.586669"
